# Default initial positions for solo12's ros2_control fake system

initial_positions:
  FL_HAA: 0.0
  FL_HFE: 0.0
  FL_KFE: 0.0
  FR_HAA: 0.0
  FR_HFE: 0.0
  FR_KFE: 0.0
  HL_HAA: 0.0
  HL_HFE: 0.0
  HL_KFE: 0.0
  HR_HAA: 0.0
  HR_HFE: 0.0
  HR_KFE: 0.0